name: Secure Action Scan - Markdown to Confluence Sync

on:
  workflow_dispatch: {}

jobs:
  fork-and-scan:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      # Step 1: Install GitHub CLI for forking
      - name: Install GitHub CLI
        run: |
          sudo apt-get update && sudo apt-get install gh -y

      # Step 2: Fork Repository if Needed
      - name: Fork Repository if Needed
        id: fork
        run: |
          echo "Forking axro-gmbh/markdown-to-confluence-sync ..."
          gh repo fork axro-gmbh/markdown-to-confluence-sync --clone=false || echo "Fork already exists"

      # Step 3: Checkout Your Repository (with .semgrep.yml)
      - name: Checkout Your Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}  # Your repo
          token: ${{ secrets.TOKEN }}

      # Step 4: Checkout the Target Repository to Scan
      - name: Checkout Forked Repository
        uses: actions/checkout@v3
        with:
          repository: axro-gmbh/markdown-to-confluence-sync
          path: target-repo
          token: ${{ secrets.TOKEN }}

      # Step 5: Run OWASP Dependency-Check via Docker
      - name: Run OWASP Dependency-Check via Docker
        run: |
          mkdir -p dependency-check-report
          docker run --rm \
            -v "$(pwd)/target-repo:/src" \
            -v "$(pwd)/dependency-check-report:/report" \
            owasp/dependency-check:latest \
            --scan /src \
            --out /report \
            --format HTML
        continue-on-error: true

      # Step 6: Run Semgrep for Data Exfiltration Vulnerability Scan
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep.yml
          scan-path: target-repo
        continue-on-error: false

      # Step 7: Finalize the Scan (always runs)
      - name: Finalize Scan
        if: always()
        run: echo "Finalizing scan. Please review previous steps for any errors."